callico-bck/callico/base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

from callico.base.mixins import PrometheusMetricsMixin
from callico.base.views import custom_set_language

handler400 = "callico.base.views.bad_request_view"
handler403 = "callico.base.views.forbidden_view"

urlpatterns = [
    path("lang/setlang/", custom_set_language, name="custom_set_language"),
    path("admin/", admin.site.urls),
    path("users/", include("callico.users.urls")),
    path("metrics", PrometheusMetricsMixin.as_view(), name="metrics"),
    path("projects/", include("callico.projects.urls")),
    path("annotation/", include("callico.annotations.urls")),
    path("processes/", include("callico.process.urls")),
    # Redirect home to projects list
    path("", RedirectView.as_view(url="/projects/"), name="home"),
    path("api/v1/", include("callico.base.api_v1")),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]


if settings.DEBUG:
    from django.conf.urls.static import static

    # Serve media files from development server
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

callico-bck/callico/projects/urls.py
from django.urls import path, re_path

from callico.projects.views import (
    AdminCampaignTasksList,
    CampaignCreate,
    CampaignDetails,
    CampaignInstructions,
    CampaignJoin,
    CampaignTasksCreate,
    CampaignTasksUnassign,
    CampaignUpdate,
    CampaignUpdateState,
    ContributorCampaignTasksList,
    ElementDetails,
    EntityFormObjectCreate,
    EntityFormObjectDelete,
    EntityFormObjectUpdate,
    InviteLinkManagement,
    ProjectBrowse,
    ProjectCreate,
    ProjectDetails,
    ProjectJoin,
    ProjectList,
    ProjectMemberCreate,
    ProjectMemberDelete,
    ProjectMemberList,
    ProjectMemberUpdate,
    ProjectUpdate,
    PublishDraftTasks,
)

urlpatterns = [
    path("", ProjectList.as_view(), name="projects"),
    path("create/", ProjectCreate.as_view(), name="project-create"),
    path("join/<invite_token>/", ProjectJoin.as_view(), name="project-join"),
    path("<uuid:project_id>/details/", ProjectDetails.as_view(), name="project-details"),
    path("<uuid:pk>/edit/", ProjectUpdate.as_view(), name="project-update"),
    path("<uuid:project_id>/members/", ProjectMemberList.as_view(), name="members"),
    path("<uuid:project_id>/members/new/", ProjectMemberCreate.as_view(), name="member-create"),
    path("<uuid:project_id>/members/<int:pk>/edit/", ProjectMemberUpdate.as_view(), name="member-update"),
    path("<uuid:project_id>/members/<int:pk>/delete/", ProjectMemberDelete.as_view(), name="member-delete"),
    path("<uuid:project_id>/invite-link/", InviteLinkManagement.as_view(), name="invite-link-management"),
    # To browse top elements in a project or children of a specific element
    re_path(
        r"^(?P<project_id>[0-9a-f-]{36})(?:/element/(?P<element_id>[0-9a-f-]{36}))?/$",
        ProjectBrowse.as_view(),
        name="project-browse",
    ),
    path("element/<uuid:pk>/", ElementDetails.as_view(), name="element-details"),
    path("<uuid:project_id>/campaign/create/", CampaignCreate.as_view(), name="campaign-create"),
    path("campaign/<uuid:pk>/", CampaignDetails.as_view(), name="campaign-details"),
    path("campaign/<uuid:pk>/instructions/", CampaignInstructions.as_view(), name="campaign-instructions"),
    path("campaign/<uuid:pk>/configure/", CampaignUpdate.as_view(), name="campaign-update"),
    path(
        "campaign/<uuid:pk>/configure/entity-form/new/",
        EntityFormObjectCreate.as_view(),
        name="entity-form-object-create",
    ),
    path(
        "campaign/<uuid:pk>/configure/entity-form/<int:position>/",
        EntityFormObjectUpdate.as_view(),
        name="entity-form-object-update",
    ),
    path(
        "campaign/<uuid:pk>/configure/entity-form/<int:position>/delete/",
        EntityFormObjectDelete.as_view(),
        name="entity-form-object-delete",
    ),
    path("campaign/<uuid:pk>/update-state/", CampaignUpdateState.as_view(), name="campaign-update-state"),
    path("campaign/<uuid:pk>/new-tasks/", CampaignTasksCreate.as_view(), name="tasks-create"),
    path("campaign/<uuid:pk>/publish-tasks/", PublishDraftTasks.as_view(), name="tasks-publish"),
    path("campaign/<uuid:pk>/tasks/", AdminCampaignTasksList.as_view(), name="admin-campaign-task-list"),
    path("campaign/<uuid:pk>/my-tasks/", ContributorCampaignTasksList.as_view(), name="contributor-campaign-task-list"),
    path("campaign/<uuid:pk>/unassign-tasks/", CampaignTasksUnassign.as_view(), name="tasks-unassign"),
    path("campaign/<uuid:pk>/join/", CampaignJoin.as_view(), name="campaign-join"),
]

callico-bck/callico/process/models.py
import json
import logging
import uuid
from datetime import datetime, timezone

from django.db import models
from django.utils.translation import gettext_lazy as _

from callico.base.celery import app

logger = logging.getLogger(__name__)

UNTRACKED = ["callico.users.tasks.send_email", "callico.users.tasks.send_daily_statistics"]


class ProcessMode(models.TextChoices):
    ArkindexImport = "arkindex_import", _("Arkindex import")
    ArkindexExport = "arkindex_export", _("Arkindex export")
    CSVExport = "csv_export", _("CSV export")
    XLSXExport = "xlsx_export", _("XLSX export")


class ProcessState(models.TextChoices):
    Created = "created", _("Created")
    Running = "running", _("Running")
    Completed = "completed", _("Completed")
    Error = "error", _("Error")


PROCESS_FINAL_STATES = [ProcessState.Completed, ProcessState.Error]


class Process(models.Model):
    # Will be manually attributed to the Celery task through apply_async(task_id=<id>)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    name = models.CharField(max_length=512, verbose_name=_("Name"))
    mode = models.CharField(max_length=32, choices=ProcessMode, verbose_name=_("Mode"))
    state = models.CharField(max_length=32, choices=ProcessState, default=ProcessState.Created, verbose_name=_("State"))
    configuration = models.JSONField(blank=True, default=dict, verbose_name=_("Configuration"))
    project = models.ForeignKey(
        "projects.Project",
        on_delete=models.CASCADE,
        related_name="processes",
        verbose_name=_("Project"),
    )
    creator = models.ForeignKey(
        "users.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="processes",
        verbose_name=_("Creator"),
    )
    logs = models.TextField(blank=True, default="", verbose_name=_("Logs"))

    created = models.DateTimeField(auto_now_add=True, verbose_name=_("Created"))
    started = models.DateTimeField(null=True, blank=True, verbose_name=_("Started"))
    ended = models.DateTimeField(null=True, blank=True, verbose_name=_("Ended"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Process")
        verbose_name_plural = _("Processes")

    @property
    def parsed_logs(self):
        splitted_logs = self.logs.split("\n")

        parsed_logs = []
        for str_obj in splitted_logs:
            try:
                parsed_logs.append(json.loads(str_obj))
            except Exception:
                continue

        return parsed_logs

    def add_log(self, log, level):
        if not logger.isEnabledFor(level):
            return

        ndjson_log = json.dumps(
            {"content": log, "level": level, "date": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")}
        )
        self.logs += f"{ndjson_log}\n"
        self.save()

        logger.log(level, log)

    def start(self):
        self.started = datetime.now(timezone.utc)
        self.state = ProcessState.Running
        self.save()

    def end(self, state=ProcessState.Completed):
        self.ended = datetime.now(timezone.utc)
        self.state = state
        self.save()

    def error(self, error):
        self.end(state=ProcessState.Error)
        self.add_log(f"An error occurred during the process {self.id}: {error}", logging.ERROR)

    def stop(self, user):
        # We don't need to stop a process that has already ended
        if self.state in PROCESS_FINAL_STATES:
            return

        app.control.revoke(str(self.id), terminate=True)
        self.end(state=ProcessState.Error)
        self.add_log(f"The process {self.id} was stopped by the user {user}", logging.ERROR)

callico-bck/callico/projects/templates/campaign_create.html
{% extends "base.html" %}
{% load i18n bulma_tags %}

{% block title %}
  {% translate "Campaign creation" %}
{% endblock title %}

{% block breadcrumb %}
  {% include "breadcrumb.html" with project=project %}
{% endblock breadcrumb %}

{% block content %}
  <a href="{% url 'project-details' project_id=project.id %}" class="button is-pulled-right">{% translate "Go back" %}</a>
  <h1 class="title">{% translate "Create a new campaign" %}</h1>

  <form method="post">
    {% csrf_token %}

    {{ form | bulma }}

    <button class="button is-success" type="submit">{% translate "Create" %}</button>
  </form>
{% endblock %}

callico-bck/callico/projects/templates/campaign_task_list_admin.html
{% extends 'base.html' %}
{% load basefilters i18n humanize bulma_tags %}

{% block title %}
  {% translate "Campaign tasks list" %}
{% endblock title %}

{% block breadcrumb %}
  {% include "breadcrumb.html" with project=campaign.project campaign=campaign can_admin=True tasks=True %}
{% endblock breadcrumb %}

{% block content %}
  <a href="{% url 'campaign-details' pk=campaign.id %}" class="button is-pulled-right">{% translate "Go back" %}</a>

  <h1 class="title">{% translate "List tasks on this campaign" %}</h1>

  {% include "progress_bar.html" %}

  {% if request.GET.state == "draft" and request.GET.user_id != "no_user" and tasks %}
    <form action="{% url 'tasks-publish' pk=campaign.id %}" method="post">
      {% csrf_token %}
      <button
        class="button is-pulled-right is-success"
        {% if campaign.is_closed %}
          disabled
          title="{% blocktranslate with state=campaign.get_state_display %}You cannot publish draft tasks for a campaign marked as {{ state }}{% endblocktranslate %}"
        {% endif %}
      >
        {% translate "Publish all draft tasks" %}
      </button>
    </form>
  {% endif %}

  <form method="get" class="is-flex is-align-items-end tasks-list-form mb-2">
    {% for field in form %}
      {{ field | bulma_horizontal }}
    {% endfor %}
    <div class="field is-horizontal">
      <button class="button is-info mb-3" type="submit">{% translate "Filter" %}</button>
    </div>
  </form>

  {% include "pagination.html" %}

  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>{% translate "Element" %}</th>
        <th>{% translate "Created" context "feminine" %}</th>
        <th>{% translate "Comments" %}</th>
        <th>{% translate "User" %}</th>
        <th class="is-narrow">{% translate "Status" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
        {% with last_task=forloop.last %}
          {% for user_task in task.user_tasks.all %}
            <tr>
              {% if forloop.first %}
                <td
                  class="truncate-long-words restricted-max-width-20 {% if last_task %}no-bottom-border{% endif %}"
                  rowspan="{{ task.user_tasks.count }}"
                  title="{{ task.element }}"
                >
                  <a href="
                           {% if not task.element.type.folder %}
                             {% url 'element-details' pk=task.element.id %}
                           {% else %}
                             {% url 'project-browse' project_id=task.element.project_id element_id=task.element.id %}
                           {% endif %}
                          ">{{ task.element|title }}</a>
                </td>
                <td
                  class="{% if last_task %}no-bottom-border{% endif %}"
                  rowspan="{{ task.user_tasks.count }}"
                >
                  <abbr title="{{ task.created }}">{{ task.created|naturaltime|capfirst }}</abbr>
                </td>
                <td
                  class="{% if last_task %}no-bottom-border{% endif %}"
                  rowspan="{{ task.user_tasks.count }}"
                >
                  <a
                    href="{% url 'task-discussion' pk=task.id %}{% querystring from='list' %}"
                    {% if task.nb_comments %}
                      title="{% blocktranslate with last=task.last_comment|naturaltime %}Last comment {{ last }}{% endblocktranslate %}"
                    {% endif %}
                  >{{ task.nb_comments|default:"−" }}</a>
                </td>
              {% endif %}
              <td class="truncate-long-words restricted-max-width-30" title="{{ user_task.user.email }}">
                {{ user_task.user }}
                {% if user_task.is_preview %}
                  {% include "preview_task_button.html" %}
                {% endif %}
              </td>
              <td>
                <div class="is-flex">
                  <span class="is-small is-light tag {{ user_task.state | task_class }} mr-3">{{ user_task.get_state_display }}</span>
                  {% if user_task.has_uncertain_value %}
                    <span class="icon has-background-warning fa-xs mr-1" title="{% translate 'The user marked this task as uncertain' %}">
                      <i class="fas fa-exclamation"></i>
                    </span>
                  {% endif %}
                </div>
              </td>
              <td>
                <div class="buttons is-justify-content-flex-end">
                  <a
                    class="button"
                    {% if not user_task.details_url %}
                      disabled
                      title="{% translate 'User task details for this campaign mode is not yet implemented' %}"
                    {% else %}
                      href="{{ user_task.details_url }}"
                    {% endif %}
                  >
                    {% translate "View details" %}
                  </a>
                  <a
                    class="button"
                    {% if user_task.task.campaign.is_closed %}
                      disabled
                      {% translate "Moderate" as action %}
                      title="{% blocktranslate with action=action|lower state=user_task.task.campaign.get_state_display %}You cannot {{ action }} a task for a campaign marked as {{ state }}{% endblocktranslate %}"
                    {% elif user_task.state == "draft" %}
                      disabled
                      title="{% blocktranslate with state=user_task.get_state_display|lower %}You cannot moderate a {{ state }} annotation{% endblocktranslate %}"
                    {% elif not user_task.moderate_url %}
                      disabled
                      title="{% translate 'Moderation for this campaign mode is not yet implemented' %}"
                    {% else %}
                      href="{{ user_task.moderate_url }}{% querystring %}"
                    {% endif %}
                  >
                    {% translate "Moderate" %}
                  </a>
                </div>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td class="truncate-long-words restricted-max-width-20" title="{{ task.element }}">
                <a href="
                         {% if not task.element.type.folder %}
                           {% url 'element-details' pk=task.element.id %}
                         {% else %}
                           {% url 'project-browse' project_id=task.element.project_id element_id=task.element.id %}
                         {% endif %}
                        ">{{ task.element|title }}</a>
              </td>
              <td>
                <abbr title="{{ task.created }}">{{ task.created|naturaltime|capfirst }}</abbr>
              </td>
              <td>
                <a
                  href="{% url 'task-discussion' pk=task.id %}{% querystring from='list' %}"
                  {% if task.nb_comments %}
                    title="{% blocktranslate with last=task.last_comment|naturaltime %}Last comment {{ last }}{% endblocktranslate %}"
                  {% endif %}
                >{{ task.nb_comments|default:"−" }}</a>
              </td>
              <td colspan="3">
                <div class="notification is-info is-light">{% translate "No user is assigned to this task" %}</div>
              </td>
            </tr>
          {% endfor %}
        {% endwith %}
      {% empty %}
        <tr>
          <td colspan="6">
            <div class="notification is-info is-light">{% translate "No task available" %}</div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

{% block script %}
  <script type="text/javascript">
    window.addEventListener('DOMContentLoaded', () => {
      callico.cleanUserTaskAnnotationStorage()
    })
  </script>
{% endblock script %}

callico-bck/callico/projects/templates/campaign_tasks_create.html
{% extends 'base.html' %}
{% load i18n bulma_tags %}

{% block title %}
  {% translate "Campaign tasks creation" %}
{% endblock title %}

{% block breadcrumb %}
  {% include "breadcrumb.html" with project=campaign.project campaign=campaign %}
{% endblock breadcrumb %}

{% block content %}
  <a href="{% url 'campaign-details' pk=campaign.id %}" class="button is-pulled-right">{% translate "Go back" %}</a>
  <h1 class="title truncate-long-words pr-4" title="{{ campaign.name }}">
    {% blocktranslate with name=campaign.name %}Create tasks on campaign "{{ name }}"{% endblocktranslate %}
  </h1>

  <div class="columns">
    <div class="column is-one-third pb-0">
      <label class="label">{% translate "Mode" %}</label>
      <p>{{ campaign.get_mode_display }}</p>
    </div>
    {% if campaign.mode == "transcription" %}
      <div class="column pb-0">
        <label class="label">{% translate "Configuration - Element types to annotate" %}</label>
        <p>
          {{ children_types|join:" · "}}
        </p>
      </div>
    {% endif %}
  </div>
  <hr />

  <form id="create-tasks-form" method="post">
    {% csrf_token %}

    {{ form | bulma }}

    <input id="preview-button" class="button is-info" type="submit" name="preview" value="{% translate 'Preview a single task' %}" />

    <button id="create-tasks-button" class="button is-success" type="submit">{% translate "Create" %}</button>
  </form>
{% endblock %}

{% block script %}
  <script type="text/javascript">
    window.addEventListener('DOMContentLoaded', () => {
      callico.bootCreateTasksForm()
    })
  </script>
{% endblock script %}

callico-bck/callico/projects/templates/element_metadata.html
{% load i18n %}

<div class="control">
  {% for key, value in user_task.task.element.metadata.items %}
    <div class="is-flex mr-3">
      <p class="truncate-long-words" title="{{ value }}">
      {% comment %}We translate the colon punctuation since it should be preceded by a space in French unlike in English{% endcomment %}
        <span class="has-text-weight-bold">{{ key }}</span><span>{% translate ": " %}</span>
        <span class="metadata-value">{{ value }}</span>
      </p>
      <i class="copy-to-clipboard fas fa-clipboard is-clickable has-text-grey" title="{% translate 'Copy the metadata value to your clipboard' %}"></i>
    </div>
  {% endfor %}
</div>

callico-bck/callico/projects/templates/element_task_list.html
{% load basefilters i18n %}

<h1 class="title">{% translate "Tasks" %}</h1>
<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>{% translate "Mode" %}</th>
      <th>{% translate "User" %}</th>
      <th class="is-narrow">{% translate "Status" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for task in element.tasks.all %}
      {% with last_task=forloop.last %}
        {% for user_task in task.user_tasks.all %}
          <tr>
            {% if forloop.first %}
              <td {% if last_task %}class="no-bottom-border" {% endif %} rowspan="{{ task.user_tasks.count }}">
                {{ task.campaign.get_mode_display }}
              </td>
            {% endif %}
            <td class="truncate-long-words restricted-max-width-50" title="{{ user_task.user.email }}">
              {{ user_task.user }}
            </td>
            <td>
              <span class="is-small is-light tag {{ user_task.state | task_class }}">
                {{ user_task.get_state_display }}
              </span>
            </td>
            <td class="has-text-right">
              {# We keep this button to allow a moderator/manager assigned to a preview task to access it #}
              {% if user_task.user == user %}
                <a
                  class="button is-success"
                  {% if user_task.task.campaign.is_closed %}
                    disabled
                    {% translate "Annotate" as action %}
                    title="{% blocktranslate with action=action|lower state=user_task.task.campaign.get_state_display %}You cannot {{ action }} a task for a campaign marked as {{ state }}{% endblocktranslate %}"
                  {% elif user_task.state == "validated" %}
                    disabled
                    title="{% translate 'You cannot change a validated annotation' %}"
                  {% elif not user_task.annotate_url %}
                    disabled
                    title="{% translate 'Annotation for this campaign mode is not yet implemented' %}"
                  {% else %}
                    href="{{ user_task.annotate_url }}"
                  {% endif %}
                >
                  {% if user_task.state == "pending" %}
                    {% translate "Annotate" %}
                  {% else %}
                    {% translate "Change annotation" %}
                  {% endif %}
                </a>
              {% else %}
                <a
                  class="button"
                  {% if not user_task.details_url %}
                    disabled
                    title="{% translate 'User task details for this campaign mode is not yet implemented' %}"
                  {% else %}
                    href="{{ user_task.details_url }}"
                  {% endif %}
                >
                  {% translate "View details" %}
                </a>
              {% endif %}
            </td>
          </tr>
        {% empty %}
          <tr>
            <td>{{ task.campaign.get_mode_display }}</td>
            <td colspan="3">
              <div class="notification is-info is-light">{% translate "No user is assigned to this task" %}</div>
            </td>
          </tr>
        {% endfor %}
      {% endwith %}
    {% empty %}
      <tr>
        <td colspan="4">
          <div class="notification is-info is-light">{% translate "No task available" %}</div>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

callico-bck/callico/projects/templates/project_details.html
{% extends 'base.html' %}
{% load i18n basefilters %}

{% block breadcrumb %}
  {% include "breadcrumb.html" with project=project %}
{% endblock breadcrumb %}

{% block title %}
  {% translate "Project details" %}
{% endblock title %}

{% block content %}

  <div class="columns">
    {% comment %}No menu for contributors & anonymous users{% endcomment %}

    {% comment %}Moderator menu - Browse elements only{% endcomment %}
    {% if can_moderate %}
      <div class="column is-2">
        <aside class="menu">
          <p class="menu-label">
            {% translate "Elements" %}
          </p>
          <ul class="menu-list">
            <li><a href="{% url 'project-browse' project_id=project.id %}">{% translate "Browse" %}</a></li>
          </ul>
        </aside>
      </div>
    {% endif %}

    {% comment %}Manager menu{% endcomment %}
    {% if can_manage %}
      <div class="column is-2">
        <aside class="menu">
          <p class="menu-label">
            {% translate "Project" %}
          </p>
          <ul class="menu-list">
            <li><a href="{% url 'project-update' pk=project.id %}">{% translate "Edit" %}</a></li>
          </ul>
          <ul class="menu-list">
            <li><a href="{% url 'members' project_id=project.id %}">{% translate "Manage members" %}</a></li>
          </ul>
          <ul class="menu-list">
            <li><a href="{% url 'invite-link-management' project_id=project.id %}">{% translate "Invite users" %}</a></li>
          </ul>
          <p class="menu-label">
            {% translate "Elements" %}
          </p>
          <ul class="menu-list">
            <li><a href="{% url 'project-browse' project_id=project.id %}">{% translate "Browse" %}</a></li>
            {% if project.provider.type == "arkindex" %}
              <li><a href="{% url 'arkindex-import-create' pk=project.id %}">{% translate "Import from Arkindex" %}</a></li>
            {% endif %}
          </ul>
          <p class="menu-label">
            {% translate "Processes" %}
          </p>
          <ul class="menu-list">
            <li><a href="{% url 'processes' pk=project.id %}">{% translate "List" %}</a></li>
          </ul>
          <p class="menu-label">
            {% translate "Campaigns" %}
          </p>
          <ul class="menu-list">
            <li><a href="{% url 'campaign-create' project_id=project.id %}">{% translate "Create" %}</a></li>
          </ul>
        </aside>
      </div>
    {% endif %}

    <div class="column {% if can_manage or can_moderate %}is-10{% else %}is-full{% endif %}">
      <div class="columns">
        {% if project.illustration %}
          <div class="column is-narrow">
            <div class="project-thumbnail-180">
              <div class="fitting-img" style='background-image: url("{{ project.illustration.url }}")'></div>
            </div>
          </div>
        {% endif %}
        <div class="column min-width-0">
          <a href="{% url 'projects' %}" class="button is-pulled-right">{% translate "Go back" %}</a>

          <h1 class="title mb-2 truncate-long-words pr-4" title="{{ project.name }}">
            {% blocktranslate with name=project.name %}Project "{{ name }}"{% endblocktranslate %}
          </h1>

          <span class="subtitle">
            {% blocktranslate with count=nb_contributors %}{{ count }} contributor(s){% endblocktranslate %}
          </span>

          {% if project.description %}
            <div class="mt-2">
              {% include "collapsable_description.html" with description=project.description %}
            </div>
          {% endif %}
        </div>
      </div>

      <hr />

      <h2 class="title is-4">{% translate "Attached campaigns" %}</h2>

      <table class="table is-fullwidth is-hoverable">
        <thead>
          <tr>
            <th>{% translate "Name" %}</th>
            <th>{% translate "Status" %}</th>
            <th>{% translate "Progress" %}</th>
            <th class="is-narrow"></th>
          </tr>
        </thead>
        <tbody>
          {% for campaign in campaigns %}
            <tr>
              <td class="truncate-long-words restricted-max-width-50" title="{{ campaign.name }}">
                {% if can_manage or can_moderate %}
                  <a href="{% url 'campaign-details' pk=campaign.id %}">{{ campaign.name }}</a>
                {% else %}
                  <span>{{ campaign.name }}</span>
                {% endif %}
              </td>
              <td><span class="is-light tag {{ campaign | campaign_class }}">{{ campaign.get_state_display }}</span></td>
              <td>
                {% if campaign.total_tasks %}
                  {% widthratio campaign.completed_tasks campaign.total_tasks 100 as completed_percentage %}
                  {{ completed_percentage }}% ({{ campaign.completed_tasks }}/{{ campaign.total_tasks }})
                {% else %}
                  -
                {% endif %}
              </td>
              <td>
                <div class="is-flex is-justify-content-right">
                  {% comment %}
                    Do only display the option to request tasks on campaigns with available tasks,
                    for non members or contributors of a project
                  {% endcomment %}
                  {% if not can_manage and not can_moderate and campaign.nb_tasks_auto_assignment %}
                    <form class="request-tasks" method="post" action="{% url 'campaign-join' pk=campaign.id %}">
                      {% csrf_token %}

                      {% translate "Request tasks" as title %}
                      {% include "request_tasks_button.html" with campaign=campaign has_pending_tasks=campaign.has_pending_tasks has_available_tasks=campaign.has_available_tasks %}
                    </form>
                  {% endif %}

                  {% if can_manage or can_moderate %}
                    <a href="{% url 'admin-campaign-task-list' pk=campaign.id %}" class="button is-light is-info">{% translate "See tasks" %}</a>
                  {% elif not campaign.is_closed %}
                    {% if campaign.has_available_tasks or project.role and campaign.has_user_tasks %}
                      {% firstof project.role|yesno:",available" campaign.has_pending_tasks|yesno:"pending," campaign.has_available_tasks|yesno:"available," as state %}
                      <a class="button is-info" href="{% url 'contributor-campaign-task-list' pk=campaign.id %}{% querystring state=state %}">
                        {% if not project.role %}
                          {% translate "The tasks" %}
                        {% else %}
                          {% translate "My tasks" %}
                        {% endif %}
                      </a>
                    {% endif %}
                  {% endif %}
                </div>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="4">
                <div class="notification is-info is-light">{% translate "No campaign available" %}</div>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}